### ISSUE TITLE
just User Friendly not a bug

### ISSUE THREAD

**Issue by hudav** [php-mongo/admin#11]
Please if the option on-click outside or ESC pressed closes the modal, it feels like a lovely  app!! :)

**Comment by hudav** [comment]
better an alpha that makes user happy, imagine the PRO!

**Comment by phpmongo** [comment]
Finally had some time for this project ;)  All modals can now be closed by clicking outside the modal frame.
All main nav features completed except for Master / Slave

**Comment by gilbert-rehling** [comment]
This suggested improvement has been implemented and tested
