### ISSUE TITLE
Hide navigation items until components ready

### ISSUE THREAD

**Issue by phpmongo** [php-mongo/admin#3]
Until each navigation item has functionality hide them so there is no confusion during Alpha testing.
We will list the full set of proposed navigation items along with screen shots on the main website fir reference.

**Comment by gilbert-rehling** [comment]
All DB related navigation elements will be visible with the next alpha release

**Comment by phpmongo** [comment]
Database nav elements have all been reactivated. The next phase of work will complete all DB panel functions
