### ISSUE TITLE
application does not load from a subfolder

### ISSUE THREAD

**Issue by gralex54** [php-mongo/admin#6]
Hello,

Trying to open the application from a subfolder. But it does not load. I have:

(fake domain) `https://example.net/phpMongoAdmin/`

I see HTML code is the following:

- Java Scripts are loaded from a wrong URL:

```
 <script src="/js/lang.js" type="text/javascript"></script>
 <script src="/js/app.js" defer></script>
```

- CSS loads fine:

```
<link href="https://example.net/phpMongoAdmin/css/app.css" rel="stylesheet">
```

Kindly advice.

Regards,
Alex.

**Comment by gilbert-rehling** [comment]
Hi, thanks for letting us know. I will have a look at that tonight and release an update.
There are also some new DB related functions ready for release...

**Comment by gilbert-rehling** [comment]
The application has now been updated to enable loading in a nested sub-directory.
Please see this page for important security information about Nested installations and Alias directive setups:
[](https://phpmongoadmin.com/support/documentation/setup/aliases-nesting-security)
If you have an ineffective nested install, please run ->  git pull to update your install, and then Crtl + F5 to force a refresh. You can then run the initial setup.
