### ISSUE TITLE
Install guide

### ISSUE THREAD

**Issue by hamboy75** [php-mongo/admin#8]
I miss an install guide.

I have unpacked it to a directory (in /var/www) and created a symbolic link for public

i get 
`
```
Warning: require(/var/www/admin-1.0.1-alpha-2.0/public/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/admin-1.0.1-alpha-2.0/public/index.php on line 24

Fatal error: require(): Failed opening required '/var/www/admin-1.0.1-alpha-2.0/public/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/admin-1.0.1-alpha-2.0/public/index.php on line 24`
```

**Comment by gilbert-rehling** [comment]
Hi,  thanks for trying our application.
Please check here for install / setup instructions: 
https://phpmongoadmin.com/support/documentation/setup

Please note:  we should be completing our final Alpha Release by next weekend.  
Check back for an update.  You should be able to run 'git pull' to fetch the updated version...

**Comment by gilbert-rehling** [comment]
We have installation and setup documentation available here: https://phpmongoadmin.com/support/documentation/setup
